package com.backend.eventsrus.enums;

public enum NotificationType {
    NEW_LEAD,
    NEW_MESSAGE,
    NEW_QUOTATION_REQUEST,
    NEW_QUOTATION_RESPONSE,
    NEW_BOOKING_PROPOSAL,
    BOOKING_APPROVED,
    BOOKING_DECLINED,
    PAYMENT_SUBMITTED,
    BOOKING_CONFIRMED,
    PAYMENT_REJECTED,
    BOOKING_CANCELLED,
    QUOTATION_DECLINED,
    BOOKING_AMENDMENT_PROPOSED,
    BOOKING_AMENDMENT_RESOLVED,
    NEW_SUPPORT_TICKET,
    SUPPORT_TICKET_REPLY,
    SUPPORT_TICKET_STATUS_CHANGED
}
