CREATE TABLE vendor_profiles (
    id                       BIGSERIAL PRIMARY KEY,
    user_id                  BIGINT NOT NULL,
    owner_name               VARCHAR(255),
    slug                     VARCHAR(255) NOT NULL,
    description              TEXT,
    logo_image_url           VARCHAR(500),
    contact_email            VARCHAR(255),
    phone_number             VARCHAR(20),
    address_line1            VARCHAR(255),
    address_line2            VARCHAR(255),
    city                     VARCHAR(100),
    state                    VARCHAR(100),
    postal_code              VARCHAR(20),
    country                  VARCHAR(100),
    id_card_key              VARCHAR(500),
    selfie_key               VARCHAR(500),
    business_permit_img_url  VARCHAR(500),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_vendor_profiles_user_id UNIQUE (user_id),
    CONSTRAINT uk_vendor_profiles_slug UNIQUE (slug),
    CONSTRAINT fk_vendor_profiles_user FOREIGN KEY (user_id) REFERENCES users(id)
);
